# Use an official OpenJDK 17 image as the base image
FROM openjdk:17-jdk-alpine
# Expose the port your application will run on (default for Spring Boot is 8080)
EXPOSE 8080
# Copy the JAR file to the container
ADD target/SpringJenkins-0.0.1-SNAPSHOT.jar /app/SpringJenkins-0.0.1-SNAPSHOT.jar
# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "SpringJenkins-0.0.1-SNAPSHOT.jar"]
